### ISSUE TITLE
Customize Crosshair, Hitmarker, and Health & Ammo displays as empty

### ISSUE THREAD

**Issue by KaIeetan** [p3tr1ch0r/insomniaHUD#21]
OS: Pop!_OS 22.04 LTS
Using the newest version of insomniaHUD updated 50 minutes ago as of March 4 1:38 PST
Using the folder name "insomniahud" for Linux compatibility

Expected behaviour: Crosshairs, hitmarkers, and health & ammo customization options should appear in the customization menu

![image](https://user-images.githubusercontent.com/31423554/222929868-2f805da9-c7b6-4bb7-bee5-0b93283751bf.png)

Scoreboard and accent colour options work as intended.

**Comment by p3tr1ch0r** [comment]
Are you doing this after joining a match? There is a bug that causes random ones to break if that is the case.

**Comment by KaIeetan** [comment]
nope, this happens on launch as well

i completely removed the folder and redownloaded the hud and it still happens as above, scoreboard and accent colour work as intended still

**Comment by KaIeetan** [comment]
Reinstalled TF2 and the hud, issue still occurs on first launch but no clue if this occurs only because the folder name is "insomniahud" (for linux support) instead of "insomniaHUD" since I can still access accent colours and scoreboard options just fine. 

No clue how the inner workings of the hud works tbh but I'm willing to compromise with manually changing the hud crosshairs and hitmarkers once I find where they're located in the first place lmfao

**Comment by p3tr1ch0r** [comment]
I'll work on a Linux support patch soon. It completely flew over my head that files were case sensitive on Linux.

**Comment by p3tr1ch0r** [comment]
Hopefully it is fixed now. Please give commit ec1c2567cd27b0ab255c3e17577a48cb0a42891e a try and let me know if it fixes the problems you've been having.

**Comment by KaIeetan** [comment]
Used latest commit (ec1c256) with complete refresh of TF2, issue still persists. 

I went through the crosshair and hitmarker files and they echo "Resource/HudLayout.res" which I'm pretty sure is aliased to the hudlayout.res file in the scripts folder? Same with the ammo and health which echo "Resource/UI/HudPlayerHealth.res" and "Resource/UI/HudAmmoWeapons.res". This might be relevant if not for the fact that this issue did not appear with the old customization menu, so I have no clue why it wouldn't work now

Accent colors
![Screenshot from 2023-03-05 23-24-41](https://user-images.githubusercontent.com/31423554/223045176-3731196b-6262-4a86-a214-33bd9f6d8c4e.png)

Crosshairs (not working)
![Screenshot from 2023-03-05 23-25-20](https://user-images.githubusercontent.com/31423554/223045194-0d461fbd-e818-44c3-8cbb-dac20b8b7c9d.png)

Hitmarkers (not working)
![Screenshot from 2023-03-05 23-27-35](https://user-images.githubusercontent.com/31423554/223045250-6c5853d6-9a69-450c-80a0-7d60d4e0ed15.png)

Scoreboard
![Screenshot from 2023-03-05 23-27-56](https://user-images.githubusercontent.com/31423554/223045545-4460a074-e396-4b50-ad76-5ab10b85bf52.png)

Health and Ammo (not working)
![Screenshot from 2023-03-05 23-28-50](https://user-images.githubusercontent.com/31423554/223045583-4523a832-18ac-4903-beaa-1fe77f3fd0fe.png)

**Comment by KaIeetan** [comment]
Got a friend to test using full lowercase name (insomniahud) on Windows, works just fine for them

**Comment by p3tr1ch0r** [comment]
This is so strange. Go to `tf/cfg/` and delete ALL files that begin with `ih_`. Open the menu and tell me what's echoed when opening the broken menus, and then tell me the contents of all `ih_` files in `tf/cfg/`.

**Comment by KaIeetan** [comment]
![Screenshot from 2023-03-06 00-22-22](https://user-images.githubusercontent.com/31423554/223056433-d840355a-5e1c-4698-a118-236774456da6.png)
![Screenshot from 2023-03-06 00-23-18](https://user-images.githubusercontent.com/31423554/223056434-f1f16478-1575-4c02-92af-af5154f82d5d.png)
![Screenshot from 2023-03-06 00-23-47](https://user-images.githubusercontent.com/31423554/223056438-14344a8b-f5cd-4441-a77f-7af5c9bda59f.png)
![Screenshot from 2023-03-06 00-25-02](https://user-images.githubusercontent.com/31423554/223056442-ffee7b1d-88ca-414f-87ee-917408b4bb1f.png)
![Screenshot from 2023-03-06 00-25-18](https://user-images.githubusercontent.com/31423554/223056444-738ee66c-c4fd-43b6-aa39-db848fc96c51.png)
![Screenshot from 2023-03-06 00-25-28](https://user-images.githubusercontent.com/31423554/223056447-25041923-ee46-486d-b354-698d6c454cda.png)
![Screenshot from 2023-03-06 00-25-40](https://user-images.githubusercontent.com/31423554/223056449-e0e07326-0582-4c9e-81b1-2eb3bdab8460.png)
![Screenshot from 2023-03-06 00-25-53](https://user-images.githubusercontent.com/31423554/223056453-2a801f40-29f6-4be4-9964-4f1a42825599.png)

**Comment by p3tr1ch0r** [comment]
Well, I'm at a loss. Everything's being echoed and written correctly. I have zero clue why some parts just aren't working. My only guess would be a path length limit, but even then that's very unlikely. I'll try and come up with a solution but I can't guarantee it.

**Comment by KaIeetan** [comment]
The most recent commit [4f1c3a6] seems to have fixed the problem!
